# Generated by Django 3.2.9 on 2021-11-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Entre com o seu nome', max_length=100)),
                ('idade', models.IntegerField()),
                ('local', models.CharField(help_text='Entre com o localização do consultório', max_length=100)),
                ('atendeOnline', models.BooleanField(help_text='Assinale se atende online')),
                ('abordagem', models.CharField(help_text='Entre com a linha que você trabalha', max_length=100)),
                ('curriculum', models.CharField(help_text='Entre com a sua formação', max_length=300)),
            ],
        ),
    ]
